enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
 disableXML: true
 minifyOutput: true

params:
  env: production

services:
  googleAnalytics:
    ID: G-LF44HZ9SEM